spring:
  datasource:
    url: jdbc:h2:mem:cruddb
    username: user
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      embedded: true
  jackson:
    serialization:
      fail-on-empty-beans: 'false'